/**
 * [app.name not defined in app.properties]
 * Admin API
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Animal
 */
export interface AnimalDto {
	description?: string;
	id?: number;
	name: string;
	type: AnimalDto.TypeEnum;
}
export namespace AnimalDto {
	export type TypeEnum = 'BIRD' | 'FISH' | 'MAMMAL' | 'REPTILE' | 'AMPHIBIAN' | 'INSECT';
	export const TypeEnum = {
		BIRD: 'BIRD' as TypeEnum,
		FISH: 'FISH' as TypeEnum,
		MAMMAL: 'MAMMAL' as TypeEnum,
		REPTILE: 'REPTILE' as TypeEnum,
		AMPHIBIAN: 'AMPHIBIAN' as TypeEnum,
		INSECT: 'INSECT' as TypeEnum
	};
}
