/**
 * [app.name not defined in app.properties]
 * Admin API
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ErrorDto {
	timestamp?: string;
	/**
     * Error code
     */
	error?: string;
	/**
     * Optional error details
     */
	errorDetails?: string;
}
