/**
 * [app.name not defined in app.properties]
 * Admin API
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnimalDto } from './AnimalDto';


export interface PageOfAnimalDto {
	content?: Array<AnimalDto>;
	first?: boolean;
	last?: boolean;
	number?: number;
	numberOfElements?: number;
	size?: number;
	sort?: any;
	totalElements?: number;
	totalPages?: number;
}
