/**
 * [app.name not defined in app.properties]
 * Admin API
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * User's data
 */
export interface UserSavingDto {
	email: string;
	firstName: string;
	/**
     * Should be null for a new user
     */
	id?: number;
	lastName: string;
	/**
     * Required for creating. For editing - when null, password will not be changed
     */
	password?: string;
	role: UserSavingDto.RoleEnum;
	username: string;
}
export namespace UserSavingDto {
	export type RoleEnum = 'ADMIN' | 'USER';
	export const RoleEnum = {
		ADMIN: 'ADMIN' as RoleEnum,
		USER: 'USER' as RoleEnum
	};
}
