package pl.itcraft.appstract.core.enums;

public enum NotificationType {

	MESSAGE,
	ORDER_ACCEPTED_BY_ABSTRACTOR,
	ORDER_SUBMITTED_FOR_APPROVAL,
	ORDER_OVERDUE,
	ORDER_DECLINED,
	ORDER_IN_PROGRESS,
	ORDER_RECALLED,
	ORDER_INCOMPLETE,
	ORDER_CANCELLED,
	ORDER_ACCEPTED_BY_ADMIN,
	ORDER_PAID,
	NEW_ORDER;
	
}
